name: dev workflow

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-test-workflow:
    uses: GNS-Science/nshm-github-actions/.github/workflows/python-run-tests.yml@main
    with:
      operating-systems: "['ubuntu-latest', 'macos-latest']"
      python-versions: "['3.8', '3.9']"
      poetry-version: 1.8.5 # last version of Poetry to support Python 3.8
    secrets: inherit
